"""Retraction rows carry no payload: nullable payload columns + two CHECKs (P2.10).

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-02

A retraction is a row (D-011): same logical key, same event-time interval,
later ``knowledge_time``, ``is_retraction = true``. Until this revision every
payload column was ``NOT NULL``, so writing one meant inventing a
``close_usd``, a ``volume_shares`` and an ``adjustment_factor`` that no source
ever stated. Those numbers sat in a fact table byte-identical to real
observations — fabricated data inside the store invariant I1 reads from
(directive §9.1/§9.2, invariant I3). Nothing downstream could tell them apart,
and neither could the storage layer.

This revision makes the absence structural rather than conventional:

1. every **payload** column of every bitemporal fact table drops its
   ``NOT NULL`` — payload meaning every column that is neither part of the
   table's logical key nor one of the five D-011 temporal/audit columns;
2. ``ck_<table>_retraction_payload_absent`` — ``NOT is_retraction OR (every
   payload column IS NULL)``. A retraction carrying a value is refused, on
   every role, session and write path, ORM or raw ``INSERT``/``COPY``;
3. ``ck_<table>_observation_payload_present`` — ``is_retraction OR (every
   required payload column IS NOT NULL)``. "Required" is exactly the set that
   was ``NOT NULL`` before this revision, so observations keep precisely the
   guarantee they had; columns a source may legitimately leave unstated
   (``period_of_report``, ``delisted_on``, ``macro_observation.value``) were
   already nullable and stay optional.

Together (2) and (3) say more than ``NOT NULL`` did: they state *which* rows
must carry values and which must not, instead of leaving the retraction case
undefined. The constraint expressions are generated by
:func:`backend.db.bitemporal._apply_payload_contract` from the ORM models and
written out verbatim here, so metadata and database agree column for column;
``backend/tests/test_bitemporal_schema.py`` fails if they drift.

NULL is the marker because it is the one thing in SQL that is not a value:
nothing compares equal to it, aggregates skip it, no arithmetic absorbs it. A
sentinel number would have been fabricated data by construction — the exact
defect being removed — and a separate retraction table would have forced the
versioned read to UNION two tables back into one knowledge-time ordering and
then split them again. The reasoning is argued in full in
``backend/db/bitemporal.py``'s module docstring.

``macro_observation.is_missing`` keeps its ``false`` server default. A
retraction must therefore state ``NULL`` for it *explicitly* (which
:func:`backend.ingest.supersession.retract_fact` and the ORM ``before_insert``
hook both do, via SQL ``NULL`` rather than Python ``None``); a raw insert that
merely omits the column takes the default and is refused by (2). That is
fail-closed and deliberate: the default is a claim about what FRED reported,
and a retraction reports nothing.

Statements are spelled out per table rather than generated from a loop, for
the same reason revisions 0003/0004/0007/0009/0010/0011 spell out their
triggers: "which columns may be NULL, and under what condition" is a question
a human answers by grepping this file.

Append-only triggers (revisions 0003/0004) are untouched and keep working —
nothing here updates or deletes a row; the ``ALTER TABLE`` statements change
column metadata and add constraints, neither of which fires a row trigger.
Both hypertables (``price_bar``, ``edgar_filing``) accept ``DROP NOT NULL``
and ``ADD CONSTRAINT ... CHECK``; TimescaleDB propagates both to existing and
future chunks.

Downgrade drops the twelve constraints and restores the ``NOT NULL``s. It
**fails loudly if any retraction row exists**, because the pre-0012 schema
cannot represent one without a fabricated payload, and inventing values to
make a downgrade succeed is the behaviour this revision exists to remove.
Retire the retractions first (the store is append-only, so that means a fresh
database) or stay on 0012.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FACT_TABLES = (
    "security_master",
    "price_bar",
    "edgar_filing",
    "edgar_filing_document",
    "macro_series",
    "macro_observation",
)
"""Every bitemporal fact table as of revision 0011, in creation order.

Used only to drop the constraints on downgrade. The upgrade statements are
written out per table so the payload of each is visible in this file.
"""

_REQUIRED_PAYLOAD: dict[str, tuple[str, ...]] = {
    "security_master": ("ticker", "name", "exchange"),
    "price_bar": (
        "open_usd",
        "high_usd",
        "low_usd",
        "close_usd",
        "volume_shares",
        "close_raw_usd",
        "adjustment_factor",
    ),
    "edgar_filing": (
        "company_name",
        "form_type",
        "filing_date",
        "index_date",
        "document_count",
        "source_url",
    ),
    "edgar_filing_document": ("document_type", "filename", "document_url"),
    "macro_series": (
        "title",
        "frequency",
        "frequency_short",
        "units",
        "units_short",
        "seasonal_adjustment_short",
        "observation_start",
        "observation_end",
        "vintage_start_date",
        "source_url",
    ),
    "macro_observation": ("is_missing", "vintage_start_date"),
}
"""Payload columns that were ``NOT NULL`` before this revision, per table.

The upgrade drops those ``NOT NULL``s and the downgrade restores exactly
them — which is why the set is stated once rather than re-derived in each
direction. Payload columns absent from this mapping were already nullable
because their source may legitimately not state them.
"""


def upgrade() -> None:
    """Drop NOT NULL on payload columns; add the retraction/observation CHECKs."""
    op.execute(
        "ALTER TABLE security_master "
        "ALTER COLUMN ticker DROP NOT NULL, "
        "ALTER COLUMN name DROP NOT NULL, "
        "ALTER COLUMN exchange DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE security_master ADD CONSTRAINT "
        "ck_security_master_retraction_payload_absent CHECK ("
        "NOT is_retraction OR (ticker IS NULL AND name IS NULL AND exchange IS NULL "
        "AND first_listed_on IS NULL AND delisted_on IS NULL))"
    )
    op.execute(
        "ALTER TABLE security_master ADD CONSTRAINT "
        "ck_security_master_observation_payload_present CHECK ("
        "is_retraction OR (ticker IS NOT NULL AND name IS NOT NULL AND exchange IS NOT NULL))"
    )

    op.execute(
        "ALTER TABLE price_bar "
        "ALTER COLUMN open_usd DROP NOT NULL, "
        "ALTER COLUMN high_usd DROP NOT NULL, "
        "ALTER COLUMN low_usd DROP NOT NULL, "
        "ALTER COLUMN close_usd DROP NOT NULL, "
        "ALTER COLUMN volume_shares DROP NOT NULL, "
        "ALTER COLUMN close_raw_usd DROP NOT NULL, "
        "ALTER COLUMN adjustment_factor DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE price_bar ADD CONSTRAINT "
        "ck_price_bar_retraction_payload_absent CHECK ("
        "NOT is_retraction OR (open_usd IS NULL AND high_usd IS NULL AND low_usd IS NULL "
        "AND close_usd IS NULL AND volume_shares IS NULL AND close_raw_usd IS NULL "
        "AND adjustment_factor IS NULL))"
    )
    op.execute(
        "ALTER TABLE price_bar ADD CONSTRAINT "
        "ck_price_bar_observation_payload_present CHECK ("
        "is_retraction OR (open_usd IS NOT NULL AND high_usd IS NOT NULL "
        "AND low_usd IS NOT NULL AND close_usd IS NOT NULL AND volume_shares IS NOT NULL "
        "AND close_raw_usd IS NOT NULL AND adjustment_factor IS NOT NULL))"
    )

    op.execute(
        "ALTER TABLE edgar_filing "
        "ALTER COLUMN company_name DROP NOT NULL, "
        "ALTER COLUMN form_type DROP NOT NULL, "
        "ALTER COLUMN filing_date DROP NOT NULL, "
        "ALTER COLUMN index_date DROP NOT NULL, "
        "ALTER COLUMN document_count DROP NOT NULL, "
        "ALTER COLUMN source_url DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE edgar_filing ADD CONSTRAINT "
        "ck_edgar_filing_retraction_payload_absent CHECK ("
        "NOT is_retraction OR (company_name IS NULL AND form_type IS NULL "
        "AND filing_date IS NULL AND index_date IS NULL AND period_of_report IS NULL "
        "AND declared_document_count IS NULL AND document_count IS NULL "
        "AND source_url IS NULL))"
    )
    op.execute(
        "ALTER TABLE edgar_filing ADD CONSTRAINT "
        "ck_edgar_filing_observation_payload_present CHECK ("
        "is_retraction OR (company_name IS NOT NULL AND form_type IS NOT NULL "
        "AND filing_date IS NOT NULL AND index_date IS NOT NULL "
        "AND document_count IS NOT NULL AND source_url IS NOT NULL))"
    )

    op.execute(
        "ALTER TABLE edgar_filing_document "
        "ALTER COLUMN document_type DROP NOT NULL, "
        "ALTER COLUMN filename DROP NOT NULL, "
        "ALTER COLUMN document_url DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE edgar_filing_document ADD CONSTRAINT "
        "ck_edgar_filing_document_retraction_payload_absent CHECK ("
        "NOT is_retraction OR (document_type IS NULL AND filename IS NULL "
        "AND description IS NULL AND document_url IS NULL))"
    )
    op.execute(
        "ALTER TABLE edgar_filing_document ADD CONSTRAINT "
        "ck_edgar_filing_document_observation_payload_present CHECK ("
        "is_retraction OR (document_type IS NOT NULL AND filename IS NOT NULL "
        "AND document_url IS NOT NULL))"
    )

    op.execute(
        "ALTER TABLE macro_series "
        "ALTER COLUMN title DROP NOT NULL, "
        "ALTER COLUMN frequency DROP NOT NULL, "
        "ALTER COLUMN frequency_short DROP NOT NULL, "
        "ALTER COLUMN units DROP NOT NULL, "
        "ALTER COLUMN units_short DROP NOT NULL, "
        "ALTER COLUMN seasonal_adjustment_short DROP NOT NULL, "
        "ALTER COLUMN observation_start DROP NOT NULL, "
        "ALTER COLUMN observation_end DROP NOT NULL, "
        "ALTER COLUMN vintage_start_date DROP NOT NULL, "
        "ALTER COLUMN source_url DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE macro_series ADD CONSTRAINT "
        "ck_macro_series_retraction_payload_absent CHECK ("
        "NOT is_retraction OR (title IS NULL AND frequency IS NULL "
        "AND frequency_short IS NULL AND units IS NULL AND units_short IS NULL "
        "AND seasonal_adjustment_short IS NULL AND observation_start IS NULL "
        "AND observation_end IS NULL AND vintage_start_date IS NULL "
        "AND vintage_end_date IS NULL AND source_url IS NULL))"
    )
    op.execute(
        "ALTER TABLE macro_series ADD CONSTRAINT "
        "ck_macro_series_observation_payload_present CHECK ("
        "is_retraction OR (title IS NOT NULL AND frequency IS NOT NULL "
        "AND frequency_short IS NOT NULL AND units IS NOT NULL AND units_short IS NOT NULL "
        "AND seasonal_adjustment_short IS NOT NULL AND observation_start IS NOT NULL "
        "AND observation_end IS NOT NULL AND vintage_start_date IS NOT NULL "
        "AND source_url IS NOT NULL))"
    )

    op.execute(
        "ALTER TABLE macro_observation "
        "ALTER COLUMN is_missing DROP NOT NULL, "
        "ALTER COLUMN vintage_start_date DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE macro_observation ADD CONSTRAINT "
        "ck_macro_observation_retraction_payload_absent CHECK ("
        "NOT is_retraction OR (value IS NULL AND is_missing IS NULL "
        "AND vintage_start_date IS NULL AND vintage_end_date IS NULL))"
    )
    op.execute(
        "ALTER TABLE macro_observation ADD CONSTRAINT "
        "ck_macro_observation_observation_payload_present CHECK ("
        "is_retraction OR (is_missing IS NOT NULL AND vintage_start_date IS NOT NULL))"
    )


def downgrade() -> None:
    """Drop the payload CHECKs and restore NOT NULL (fails if retractions exist).

    The ``SET NOT NULL`` statements raise on any fact table holding a
    retraction row, because those rows have NULL payloads and the pre-0012
    schema has no way to hold them that is not a fabricated value. That
    failure is the correct outcome, not an oversight — see the module
    docstring.
    """
    for table in _FACT_TABLES:
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT ck_{table}_observation_payload_present")
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT ck_{table}_retraction_payload_absent")
    for table, columns in _REQUIRED_PAYLOAD.items():
        clauses = ", ".join(f"ALTER COLUMN {column} SET NOT NULL" for column in columns)
        op.execute(f"ALTER TABLE {table} {clauses}")
