"""Synthetic-truth harness for the validation framework (P10.2-P10.4).

Directive §5, gate G10:

    *"Framework reproduces known results on synthetic data with injected signal
    of known strength — and correctly reports near-zero signal on pure noise.
    This second test is the critical one. If your framework finds alpha in
    random data, it is broken and everything downstream is fiction."*

Everything in this module is generated by a seeded
:class:`numpy.random.Generator`, so the "random" data is fixed and every
assertion below is deterministic — there is no flaky tolerance and no lucky
draw. Invariant I2 in test form: the same seeds give the same numbers on every
machine and every run.

Two ways of getting the noise direction wrong, both guarded here:

* **One seed is not evidence.** A single noise draw can produce a PBO of 0.05 or
  0.95; the seed-to-seed standard deviation of PBO on pure noise is about 0.2.
  Every claim below is made about the *distribution* over many seeds, never
  about one run.
* **A weak assertion is not a test.** Asserting "PBO is not exactly 0" would
  pass on a broken framework. The assertions are two-sided and quantified: the
  mean over seeds sits at 0.5 within a stated margin, and the deflated Sharpe
  ratio certifies nothing at the 95% level in any of them.

The signal direction uses a strategy whose true per-period Sharpe ratio is known
in closed form, derived in
:func:`test_cpcv_path_distribution_is_centred_on_the_injected_true_sharpe`.

Cost realism (I4): these are synthetic P&L series, not gross returns from a
market. The harness treats them as already net of modelled costs — which is what
every function in :mod:`backend.backtest` requires of its input — and a constant
cost drag would shift every number in the same direction without changing what
is being tested here.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from backend.backtest.cpcv import (
    CombinatorialPurgedCV,
    CPCVSplits,
    PathDistribution,
    path_sharpe_ratios,
)
from backend.backtest.dsr import deflated_sharpe_ratio_from_returns
from backend.backtest.metrics import FloatArray, sharpe_ratio
from backend.backtest.pbo import probability_of_backtest_overfitting

# --- shared parameters ------------------------------------------------------

_N_SEEDS = 200
"""Seeds per noise claim. The per-seed spread of PBO on noise is ~0.2, so the
standard error of the mean over 200 seeds is ~0.015 — small enough that a
framework biased by 0.05 would be caught."""

_OBSERVATIONS = 1008
"""Four years of daily observations."""

_DAILY_VOLATILITY = 0.01
"""1% per day, roughly a liquid equity long-short book."""


def _noise_matrix(seed: int, *, n_configurations: int) -> FloatArray:
    """Return per-period returns for candidates with **no** true edge whatsoever.

    Every column is iid zero-mean Gaussian noise. Nothing distinguishes the
    candidates, so any framework that reports skill here is reporting an artefact
    of its own construction.
    """
    generator = np.random.default_rng(seed)
    return generator.normal(0.0, _DAILY_VOLATILITY, size=(_OBSERVATIONS, n_configurations)).astype(
        np.float64
    )


# ---------------------------------------------------------------------------
# Direction 1 — pure noise must report no skill
# ---------------------------------------------------------------------------


def test_pbo_on_pure_noise_is_centred_on_one_half() -> None:
    """Selecting the in-sample winner among noise candidates is a coin flip.

    With ``N`` exchangeable candidates and in-sample and out-of-sample
    performance computed on disjoint rows, the winner's out-of-sample rank is
    uniform on ``1..N``. For even ``N`` the probability of landing at or below
    the median is therefore exactly 1/2, and PBO estimates that probability.
    """
    values = np.array(
        [
            probability_of_backtest_overfitting(
                _noise_matrix(1000 + seed, n_configurations=10), n_partitions=10
            ).pbo
            for seed in range(_N_SEEDS)
        ]
    )

    assert values.mean() == pytest.approx(0.5, abs=0.06)
    assert float(np.median(values)) == pytest.approx(0.5, abs=0.10)
    # Neither systematically optimistic nor systematically pessimistic.
    assert 0.35 <= float(np.mean(values > 0.5)) <= 0.65
    # And the seed-to-seed spread is wide, which is exactly why a single run is
    # not evidence. If this ever collapsed towards zero the assertions above
    # would have become vacuous.
    assert values.std(ddof=1) > 0.1
    assert values.min() < 0.2
    assert values.max() > 0.8


def test_a_deflated_sharpe_ratio_certifies_nothing_on_pure_noise() -> None:
    """The best of many noise trials must not survive its own trial count.

    The strategy reported here is the *winner of a search over 200 candidates*,
    every one of which is worthless. Its raw Sharpe ratio is comfortably
    positive — that is what searching does — and the Deflated Sharpe Ratio is
    the statistic that has to see through it.
    """
    honest: list[float] = []
    raw_sharpes: list[float] = []
    for seed in range(_N_SEEDS):
        matrix = _noise_matrix(2000 + seed, n_configurations=200)
        trial_sharpes = np.array([sharpe_ratio(matrix[:, j]) for j in range(matrix.shape[1])])
        best = int(np.argmax(trial_sharpes))
        raw_sharpes.append(float(trial_sharpes[best]))
        honest.append(
            deflated_sharpe_ratio_from_returns(
                matrix[:, best],
                trials=matrix.shape[1],
                trial_sharpe_variance=float(np.var(trial_sharpes, ddof=1)),
            ).value
        )
    deflated = np.array(honest)

    # The search really did manufacture an impressive-looking result: a
    # per-period Sharpe of ~0.08 is ~1.3 annualized, on data with no edge at all.
    assert min(raw_sharpes) > 0.04
    assert np.mean(raw_sharpes) * math.sqrt(252) > 1.0

    # The deflated number sits at a coin flip, which is the correct answer: the
    # observed maximum is about what a search of this size produces by luck.
    assert deflated.mean() == pytest.approx(0.5, abs=0.1)
    # And it certifies essentially nothing at the conventional 95% level.
    assert float(np.mean(deflated >= 0.95)) <= 0.02
    assert float(np.mean(deflated >= 0.99)) == 0.0


def test_pretending_a_single_trial_certifies_that_same_noise_almost_always() -> None:
    """Why the trial count is a required argument and never defaults to 1.

    Identical data, identical returns, identical formula — the only difference is
    a trial count of 1 instead of the true 200. The result flips from "coin
    flip" to "certain", on data with no edge in it. This is the most misleading
    number this system could emit, and the only defence is that ``trials`` can
    never be omitted.
    """
    undeflated: list[float] = []
    for seed in range(_N_SEEDS):
        matrix = _noise_matrix(2000 + seed, n_configurations=200)
        trial_sharpes = np.array([sharpe_ratio(matrix[:, j]) for j in range(matrix.shape[1])])
        best = int(np.argmax(trial_sharpes))
        undeflated.append(
            deflated_sharpe_ratio_from_returns(
                matrix[:, best], trials=1, trial_sharpe_variance=0.0
            ).value
        )
    values = np.array(undeflated)

    assert float(np.mean(values >= 0.95)) >= 0.9
    assert values.mean() > 0.95


# ---------------------------------------------------------------------------
# The CPCV harness — a model refitted on every split
# ---------------------------------------------------------------------------

_HORIZON = 5.0
"""Label horizon in observation periods: each label resolves five periods out, so
training labels overlapping a test block are purged and the five periods after
one are embargoed."""

_N_GROUPS = 6
_N_TEST_GROUPS = 2


def _cpcv_paths(
    seed: int, *, beta: FloatArray, noise_volatility: float
) -> tuple[PathDistribution, CPCVSplits, FloatArray]:
    """Run a full CPCV backtest of a linear strategy over synthetic data.

    Three iid standard-normal features drive the outcome
    ``r_t = beta . x_t + e_t``. Only the first two coefficients are non-zero; the
    third feature is a decoy with no relationship to the outcome, so the fitted
    model has something to overfit to.

    On every split the model is refitted by least squares on that split's
    **purged and embargoed** training rows only, and the strategy's per-period
    P&L on a test row is ``(beta_hat . x_t) * r_t`` — position proportional to
    the forecast, marked at the realized outcome. The per-split out-of-sample
    P&L is then reassembled into ``C(N-1, k-1)`` complete paths.

    The paths differ from one another because each group's forecast comes from a
    differently-trained model; that is the estimation risk a single walk-forward
    path hides.
    """
    generator = np.random.default_rng(seed)
    features = generator.standard_normal((_OBSERVATIONS, 3))
    outcomes = features @ beta + generator.normal(0.0, noise_volatility, size=_OBSERVATIONS)

    cv = CombinatorialPurgedCV(n_groups=_N_GROUPS, n_test_groups=_N_TEST_GROUPS, embargo=_HORIZON)
    starts = np.arange(_OBSERVATIONS, dtype=np.float64)
    splits = cv.split(starts, starts + _HORIZON)

    per_split: list[FloatArray] = []
    for split in splits:
        fitted, *_ = np.linalg.lstsq(
            features[split.train_indices], outcomes[split.train_indices], rcond=None
        )
        positions = features[split.test_indices] @ fitted
        per_split.append(positions * outcomes[split.test_indices])

    paths = splits.assemble_paths(per_split)
    return path_sharpe_ratios(paths), splits, paths


def _true_sharpe(beta: FloatArray, noise_volatility: float) -> float:
    """Return the per-period Sharpe ratio of the strategy run with the true beta.

    With ``q_t = beta . x_t ~ N(0, s2)`` where ``s2 = |beta|**2``, and
    ``r_t = q_t + e_t`` with ``e_t ~ N(0, sigma**2)`` independent of ``x_t``, the
    P&L of the position ``q_t`` is ``g_t = q_t * (q_t + e_t)``, so

        E[g]   = E[q**2]                                  = s2
        Var[g] = Var(q**2) + Var(q e)                     = 2 * s2**2 + s2 * sigma**2

    (the cross term vanishes because ``E[q**3 e] = 0``), giving

        SR = s2 / sqrt(2 * s2**2 + s2 * sigma**2)
           = sqrt(s2) / sqrt(2 * s2 + sigma**2)

    per observation period. This is a property of the data-generating process,
    computed without reference to anything in :mod:`backend.backtest`.
    """
    s2 = float(beta @ beta)
    return s2 / math.sqrt(2.0 * s2**2 + s2 * noise_volatility**2)


# ---------------------------------------------------------------------------
# Direction 1 continued — CPCV on noise
# ---------------------------------------------------------------------------


def test_cpcv_paths_on_pure_noise_are_centred_on_zero() -> None:
    """A model fitted on noise must not produce a positive out-of-sample path.

    The regression here has three features and roughly 600 training rows per
    split, so it fits *something* every time — the in-sample fit is never zero.
    Purged, embargoed, out-of-sample evaluation has to give that back.
    """
    beta = np.zeros(3)
    means = np.array(
        [_cpcv_paths(3000 + seed, beta=beta, noise_volatility=0.02)[0].mean for seed in range(40)]
    )

    standard_error = float(means.std(ddof=1)) / math.sqrt(means.size)
    assert abs(float(means.mean())) < 2.5 * standard_error
    assert abs(float(means.mean())) < 0.02
    # Annualized, the average path Sharpe on noise stays inside +/- 0.5 — nowhere
    # near anything a human would act on.
    assert abs(float(means.mean())) * math.sqrt(252) < 0.5
    # No individual seed produces a path distribution that looks like an edge.
    assert float(np.max(np.abs(means))) < 0.1


def test_the_noise_harness_would_notice_a_signal_if_there_were_one() -> None:
    """The zero result above is not an artefact of a harness that always returns zero.

    Same code, same seeds, same sample size — the only change is a non-zero beta.
    Without this, ``test_cpcv_paths_on_pure_noise_are_centred_on_zero`` would pass
    just as happily against a harness that always reported nothing.
    """
    beta = np.array([0.003, 0.003, 0.0])
    with_signal = np.array(
        [_cpcv_paths(3000 + seed, beta=beta, noise_volatility=0.02)[0].mean for seed in range(40)]
    )
    without = np.array(
        [
            _cpcv_paths(3000 + seed, beta=np.zeros(3), noise_volatility=0.02)[0].mean
            for seed in range(40)
        ]
    )
    assert float(with_signal.mean()) > 0.15
    assert float(with_signal.min()) > float(without.max())


# ---------------------------------------------------------------------------
# Direction 2 — an injected signal of known strength must be recovered
# ---------------------------------------------------------------------------


def test_cpcv_path_distribution_is_centred_on_the_injected_true_sharpe() -> None:
    """The recovered distribution must sit on the true Sharpe ratio, not near it by luck.

    ``beta = (0.003, 0.003, 0)`` against residual volatility 0.02 gives, by the
    closed form in :func:`_true_sharpe`,

        s2 = 0.003**2 + 0.003**2 = 1.8e-05
        SR = 1.8e-05 / sqrt(2 * (1.8e-05)**2 + 1.8e-05 * 0.0004)
           = 0.2031856384435789   per period

    The measured mean over 40 seeded runs is compared against that number.
    """
    beta = np.array([0.003, 0.003, 0.0])
    truth = _true_sharpe(beta, 0.02)
    assert truth == pytest.approx(0.2031856384435789, rel=1e-12)

    means: list[float] = []
    spreads: list[float] = []
    for seed in range(40):
        distribution, splits, _ = _cpcv_paths(seed, beta=beta, noise_volatility=0.02)
        assert len(distribution) == splits.n_paths == math.comb(_N_GROUPS - 1, _N_TEST_GROUPS - 1)
        means.append(distribution.mean)
        spreads.append(distribution.std)
    recovered = np.array(means)

    # Centred on the truth: the grand mean is within one standard error of it.
    standard_error = float(recovered.std(ddof=1)) / math.sqrt(recovered.size)
    assert abs(float(recovered.mean()) - truth) < 2.5 * standard_error
    assert float(recovered.mean()) == pytest.approx(truth, rel=0.10)

    # Slightly *below* the truth, and that is correct rather than a defect: the
    # model is estimated, not known, and an estimated coefficient vector is never
    # better aligned with the outcome than the true one. A framework reporting
    # more than the injected strength out-of-sample would be leaking.
    assert float(recovered.mean()) < truth

    # Every seed lands in the same neighbourhood — no seed reports nothing, and
    # none reports an edge that is not there.
    assert float(recovered.min()) > 0.6 * truth
    assert float(recovered.max()) < 1.4 * truth

    # And it is a distribution, not a point estimate: refitting the model per
    # split genuinely moves the paths apart.
    assert min(spreads) > 0.0


def test_a_stronger_injected_signal_is_recovered_as_a_stronger_one() -> None:
    """Recovery must track the injected strength monotonically, not just be positive."""
    recovered: list[float] = []
    truths: list[float] = []
    for scale in (0.0015, 0.003, 0.006):
        beta = np.array([scale, scale, 0.0])
        truths.append(_true_sharpe(beta, 0.02))
        recovered.append(
            float(
                np.mean(
                    [
                        _cpcv_paths(seed, beta=beta, noise_volatility=0.02)[0].mean
                        for seed in range(20)
                    ]
                )
            )
        )
    assert truths == sorted(truths)
    assert recovered == sorted(recovered)
    for measured, truth in zip(recovered, truths, strict=True):
        assert measured == pytest.approx(truth, rel=0.2)


def test_the_recovered_distribution_reports_an_interval_rather_than_a_point() -> None:
    """Directive §10: no point estimate is ever displayed alone."""
    beta = np.array([0.003, 0.003, 0.0])
    distribution, splits, _ = _cpcv_paths(11, beta=beta, noise_volatility=0.02)

    summary = distribution.describe()
    assert summary["n_paths"] == float(splits.n_paths)
    lower, upper = distribution.confidence_interval(0.95)
    assert lower <= summary["median"] <= upper
    assert summary["ci_lower"] == lower
    assert summary["ci_upper"] == upper
    assert summary["min"] <= summary["mean"] <= summary["max"]


def test_the_injected_signal_survives_its_own_trial_count() -> None:
    """A real edge, honestly deflated against a realistic search, still certifies.

    The mirror image of the noise test: if the Deflated Sharpe Ratio rejected
    everything, "it rejects noise" would be worthless. Here a genuine edge is
    deflated against 200 declared trials whose Sharpe ratios are as spread out as
    the noise search's, and it survives.
    """
    beta = np.array([0.003, 0.003, 0.0])
    distribution, _, paths = _cpcv_paths(7, beta=beta, noise_volatility=0.02)

    # Deflate a real out-of-sample path — the same net-of-cost series the path
    # Sharpe distribution was computed from, not a reconstruction of it.
    realized = paths[0]
    assert sharpe_ratio(realized) == pytest.approx(distribution.values[0], rel=1e-12)

    # Deflated against a search as large and as varied as the noise search above.
    result = deflated_sharpe_ratio_from_returns(realized, trials=200, trial_sharpe_variance=0.0009)
    assert result.trials == 200
    assert result.expected_maximum_sharpe > 0.0
    assert result.observed_sharpe > result.expected_maximum_sharpe
    assert result.value > 0.95
